### ISSUE TITLE
json-ice crashes if field not annotated

### ISSUE THREAD

**Issue by dkegel-fastly** [moznion/go-json-ice#24]
Looks like go-json-ice requires annotation of each field.  This is inconvenient, as other serializers have a sensible default.

To reproduce, remove the annotation from one field in the example in README, then do
```go generate```
This fails with
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x11f4576]

goroutine 1 [running]:
main.main()
	/Users/dkegel/go/pkg/mod/github.com/moznion/go-json-ice@v0.0.2/cmd/json-ice/main.go:182 +0xc76
main.go:6: running "json-ice": exit status 2
```

At the very least, it should not crash, and should print an error saying that annotation is mandatory.

Better would be to behave as other serializers do, and default to the same name as the field for the json key.

**Comment by moznion** [comment]
Hi, @dkegel-fastly!

Thank you for your reporting. This unexpected behavior has been fixed by #25 and I've released the patched version [v0.0.3](https://github.com/moznion/go-json-ice/releases/tag/v0.0.3).
